name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}

      - uses: actions/checkout@v2

      - name: clippy
        run: make clippy

      - name: Build
        run: make build

      - name: Run tests
        run: make test
